"use client";
import React, { useState } from 'react';
import { ChevronDown, ChevronUp, FileText, Calendar, Users, Building, Truck, ArrowRight, ArrowLeft } from 'lucide-react';

const GSTInfoPage = () => {
  const [openSection, setOpenSection] = useState(null);

  const toggleSection = (section) => {
    setOpenSection(openSection === section ? null : section);
  };

  const gstReturns = [
    {
      id: 'gstr1',
      title: 'GSTR-1',
      subtitle: 'Outward Supplies Return',
      icon: <FileText className="w-6 h-6" />,
      description: 'GSTR-1 is a monthly or quarterly return that contains details of all outward supplies of goods and services made by a registered taxpayer. This return forms the basis for availment of input tax credit by the recipients.',
      details: [
        'Filed by all regular GST taxpayers',
        'Monthly filing for turnover > ₹5 crores',
        'Quarterly filing for turnover ≤ ₹5 crores',
        'Due date: 11th of next month (monthly) / 13th of month following quarter (quarterly)',
        'Contains details of B2B, B2C, exports, and other outward supplies'
      ],
      dueDate: '11th/13th of following month/quarter',
      applicableTo: 'All regular GST taxpayers'
    },
    {
      id: 'gstr2a',
      title: 'GSTR-2A',
      subtitle: 'Auto-populated Purchase Return',
      icon: <ArrowRight className="w-6 h-6" />,
      description: 'GSTR-2A is an auto-populated return that shows all inward supplies for which Input Tax Credit (ITC) can be availed. It is generated based on the outward supplies reported by suppliers in their GSTR-1.',
      details: [
        'Auto-generated by the GST system',
        'No filing required by taxpayer',
        'Updated dynamically as suppliers file GSTR-1',
        'Basis for claiming Input Tax Credit',
        'Contains supplier-wise purchase details'
      ],
      dueDate: 'Auto-generated (No filing required)',
      applicableTo: 'Available to all GST registered taxpayers'
    },
    {
      id: 'gstr2b',
      title: 'GSTR-2B',
      subtitle: 'Static Input Tax Credit Statement',
      icon: <Building className="w-6 h-6" />,
      description: 'GSTR-2B is a static statement that shows eligible Input Tax Credit for a tax period. Unlike GSTR-2A, it remains unchanged after generation and provides a clear picture of ITC available for a specific period.',
      details: [
        'Generated on 12th of following month',
        'Static document - does not change after generation',
        'Shows eligible ITC for the tax period',
        'Includes details from GSTR-1, GSTR-5, GSTR-6, GSTR-8',
        'More reliable than GSTR-2A for ITC calculation'
      ],
      dueDate: '12th of following month (Auto-generated)',
      applicableTo: 'All regular GST taxpayers'
    },
    {
      id: 'gstr3b',
      title: 'GSTR-3B',
      subtitle: 'Monthly Summary Return',
      icon: <Calendar className="w-6 h-6" />,
      description: 'GSTR-3B is a summary return filed monthly by regular taxpayers. It contains summary of outward supplies, input tax credit claimed, and tax payable. This is a critical return as tax payment is made through this return.',
      details: [
        'Monthly filing by all regular taxpayers',
        'Summary of outward and inward supplies',
        'Input Tax Credit claimed and tax liability',
        'Due date: 20th of following month',
        'Tax payment made through this return',
        'Late fee applicable for delayed filing'
      ],
      dueDate: '20th of following month',
      applicableTo: 'All regular GST taxpayers'
    },
    {
      id: 'gstr4',
      title: 'GSTR-4',
      subtitle: 'Composition Scheme Return',
      icon: <Users className="w-6 h-6" />,
      description: 'GSTR-4 is a quarterly return filed by taxpayers registered under the Composition Scheme. It contains details of supplies made during the quarter and tax paid under the composition scheme.',
      details: [
        'Filed by composition scheme taxpayers',
        'Quarterly filing requirement',
        'Due date: 18th of month following quarter',
        'Contains summary of supplies and tax paid',
        'Simplified return with minimal compliance'
      ],
      dueDate: '18th of month following quarter',
      applicableTo: 'Composition scheme taxpayers'
    },
    {
      id: 'gstr7',
      title: 'GSTR-7',
      subtitle: 'Tax Deducted at Source Return',
      icon: <Truck className="w-6 h-6" />,
      description: 'GSTR-7 is filed by persons required to deduct tax at source under GST. This includes government departments, PSUs, and specified entities that deduct tax while making payments to suppliers.',
      details: [
        'Filed by TDS deductors under GST',
        'Monthly filing requirement',
        'Due date: 10th of following month',
        'Contains details of TDS deducted and deposited',
        'Applicable to government entities and specified organizations'
      ],
      dueDate: '10th of following month',
      applicableTo: 'Government departments, PSUs, and specified TDS deductors'
    }
  ];

  const additionalComponents = [
    {
      title: 'GSTR-5',
      description: 'Filed by Non-Resident Foreign Taxpayers for supplies made in India',
      dueDate: '20th of following month'
    },
    {
      title: 'GSTR-6',
      description: 'Filed by Input Service Distributors for distribution of input tax credit',
      dueDate: '13th of following month'
    },
    {
      title: 'GSTR-8',
      description: 'Filed by e-commerce operators for supplies made through their platform',
      dueDate: '10th of following month'
    },
    {
      title: 'GSTR-9',
      description: 'Annual return filed by regular taxpayers containing annual summary',
      dueDate: '31st December of following financial year'
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-blue-50">
      {/* Header Section */}
      <div className="bg-white shadow-sm border-b border-blue-100">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          {/* Back Button */}
          <div className="mb-6">
            <button 
              onClick={() => window.history.back()}
              className="flex items-center text-blue-600 hover:text-blue-700 transition-colors duration-200"
            >
              <ArrowLeft className="w-5 h-5" />
            </button>
          </div>
          
          <div className="text-center">
            <h1 className="text-4xl font-bold text-gray-900 mb-4">
              Goods and Services Tax (GST) Returns
            </h1>
            <p className="text-xl text-gray-600 max-w-3xl mx-auto">
              Comprehensive guide to GST return filing requirements, due dates, and compliance obligations 
              for different categories of taxpayers under the GST regime in India.
            </p>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        
        {/* Introduction */}
        <div className="bg-white rounded-xl shadow-lg p-8 mb-12 border border-blue-100">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">Understanding GST Returns</h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            The Goods and Services Tax (GST) system in India requires registered taxpayers to file periodic returns 
            containing details of their business transactions. These returns serve multiple purposes including tax 
            compliance, input tax credit mechanism, and revenue collection for the government.
          </p>
          <p className="text-gray-700 leading-relaxed">
            Each type of GST return serves a specific purpose and has different filing requirements, due dates, and 
            applicability criteria. Understanding these requirements is crucial for maintaining GST compliance and 
            avoiding penalties.
          </p>
        </div>

        {/* Main GST Returns */}
        <div className="space-y-6 mb-12">
          {gstReturns.map((returnForm) => (
            <div key={returnForm.id} className="bg-white rounded-xl shadow-lg border border-blue-100 overflow-hidden">
              <div 
                className="p-6 cursor-pointer hover:bg-blue-50 transition-colors duration-200"
                onClick={() => toggleSection(returnForm.id)}
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-4">
                    <div className="flex-shrink-0 w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center text-blue-600">
                      {returnForm.icon}
                    </div>
                    <div>
                      <h3 className="text-xl font-semibold text-gray-900">{returnForm.title}</h3>
                      <p className="text-blue-600 font-medium">{returnForm.subtitle}</p>
                    </div>
                  </div>
                  {openSection === returnForm.id ? 
                    <ChevronUp className="w-5 h-5 text-gray-500" /> : 
                    <ChevronDown className="w-5 h-5 text-gray-500" />
                  }
                </div>
              </div>
              
              {openSection === returnForm.id && (
                <div className="px-6 pb-6 border-t border-blue-100 bg-blue-50/30">
                  <div className="pt-6">
                    <p className="text-gray-700 mb-6 leading-relaxed">
                      {returnForm.description}
                    </p>
                    
                    <div className="grid md:grid-cols-2 gap-6">
                      <div>
                        <h4 className="font-semibold text-gray-900 mb-3">Key Features:</h4>
                        <ul className="space-y-2">
                          {returnForm.details.map((detail, index) => (
                            <li key={index} className="flex items-start space-x-2">
                              <div className="w-2 h-2 bg-blue-500 rounded-full mt-2 flex-shrink-0"></div>
                              <span className="text-gray-700">{detail}</span>
                            </li>
                          ))}
                        </ul>
                      </div>
                      
                      <div className="space-y-4">
                        <div className="bg-white p-4 rounded-lg border border-blue-200">
                          <h5 className="font-semibold text-gray-900 mb-2">Due Date</h5>
                          <p className="text-blue-600 font-medium">{returnForm.dueDate}</p>
                        </div>
                        <div className="bg-white p-4 rounded-lg border border-blue-200">
                          <h5 className="font-semibold text-gray-900 mb-2">Applicable To</h5>
                          <p className="text-gray-700">{returnForm.applicableTo}</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>

        {/* Additional GST Returns */}
        <div className="bg-white rounded-xl shadow-lg p-8 border border-blue-100">
          <h2 className="text-2xl font-bold text-gray-900 mb-6">Other GST Returns</h2>
          <div className="grid md:grid-cols-2 gap-6">
            {additionalComponents.map((component, index) => (
              <div key={index} className="bg-blue-50 p-6 rounded-lg border border-blue-200">
                <h3 className="text-lg font-semibold text-gray-900 mb-3">{component.title}</h3>
                <p className="text-gray-700 mb-4">{component.description}</p>
                <div className="text-sm">
                  <span className="font-medium text-gray-900">Due Date: </span>
                  <span className="text-blue-600">{component.dueDate}</span>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Important Notes */}
        <div className="bg-gradient-to-r from-blue-400 to-blue-600 rounded-xl shadow-lg p-8 mt-12 text-white">
          <h2 className="text-2xl font-bold mb-4">Important Compliance Notes</h2>
          <div className="grid md:grid-cols-2 gap-6">
            <div>
              <h3 className="font-semibold mb-3">Filing Requirements</h3>
              <ul className="space-y-2 text-blue-100">
                <li>• Returns must be filed even if there are no transactions (Nil returns)</li>
                <li>• Late filing attracts penalty and interest charges</li>
                <li>• Digital signature or EVC required for filing</li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold mb-3">Best Practices</h3>
              <ul className="space-y-2 text-blue-100">
                <li>• Maintain proper books of accounts and supporting documents</li>
                <li>• Reconcile data regularly to avoid discrepancies</li>
                <li>• File returns within due dates to avoid penalties</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default GSTInfoPage;